### ISSUE TITLE
Visualizer panel doesn't show objects when other panel is stacked on top of visualizer panel.

### ISSUE THREAD

**Issue by parksong22** [YPM-Informatics/COPISClient#15]
![image](https://user-images.githubusercontent.com/48225300/85165227-80ab2f00-b233-11ea-9bc6-be3a20735c78.png)

When a panel is moved to where visualizer panel is and you click visualizer tab, 3D objects are disappeared from visualizer panel.

**Comment by k3vnchen** [comment]
What's the wx event associated with moving a panel "into" another? Trying to figure out why it's blank - EVT_PAINT should have triggered

**Comment by parksong22** [comment]
Like you can see in the screenshot, I moved command panel in a visualizer panel's location. Now they are in a same dock -- right dock has two panels now, visualizer and command.
