### ISSUE TITLE
Refresh button and virtual cameras

### ISSUE THREAD

**Issue by XRuiz9** [YPM-Informatics/COPISClient#23]
Clicking the refresh button repeatedly cause virtual cameras to disappear/reappear or be selected/deselected. Sometimes it will clear the combo box of virtual cameras as well.

**Comment by k3vnchen** [comment]
Seems to be an issue when [`onClearCanvas()`](https://github.com/YPM-Informatics/COPISClient/blob/develop/panels/visualizerPanel.py#L58-L60) in `visualizerPanel` is called from `controllerPanel`. I think we could add a `Refresh()` there? @parksong22 what does `SwapBuffers()` do?
