### ISSUE TITLE
The serial preferences window should be a dialog, not a frame

### ISSUE THREAD

**Issue by XRuiz9** [YPM-Informatics/COPISClient#39]
Our code is currently written in a way that going under the menu bar and clicking tools>generate path or configuration>preferences multiples times instantiates new frames. If one is already open, it should just set the current open frame to active instead of a creating duplicates.

**Comment by inchkev** [comment]
Note: this isn't an issue for path generation anymore after #101 is merged. For the preferences window, we should just make it into a dialog
