### ISSUE TITLE
Implement serial port communications in copiscore

### ISSUE THREAD

**Issue by k3vnchen** [YPM-Informatics/COPISClient#54]
- Implement connect/disconnect to serial port
- Link with toolbar baud/port selection

**Comment by nelsonrios** [comment]
For version 1 we can probably play it safe and send commands one at a time. In other words send command (either one cam at a time or batch all 1-6 cames at a time), wait for response, send next command batch, rinse repeat. This would simplify keeping things in sync.

**Comment by djihbril** [comment]
Reimplemented as part of user story #71.
