### ISSUE TITLE
Implement command sending to device and cameras in copiscore

### ISSUE THREAD

**Issue by k3vnchen** [YPM-Informatics/COPISClient#59]
- Read action list to send commands to the device via serial port or cameras via edsdk
- Read from serial port for confirmation for syncing commands (@nelsonrios you can probably elaborate here)
- Link toolbar play/pause/stop buttons to copiscore when completed

**Comment by djihbril** [comment]
This issue has been categorized.

Reimplemented as user story in #71 & #75
