### ISSUE TITLE
Implement config manager, create application and device configs

### ISSUE THREAD

**Issue by k3vnchen** [YPM-Informatics/COPISClient#61]
- Complete `appconfig.py`
- Application config file (nonessential: GUI settings, visual/color settings, etc.)
- Device config file (chamber dimensions, camera boundaries, camera initial positions, etc.)
- Create preferences window(s) to modify these settings in the GUI

**Comment by djihbril** [comment]
This issue has been categorized.

**Comment by djihbril** [comment]
Reimplemented as user story #66.
