### ISSUE TITLE
Wire appropriate commands to toolbar action buttons

### ISSUE THREAD

**Issue by djihbril** [YPM-Informatics/COPISClient#74]
Toolbar components are:
* [x] play button
* [x] pause button
* [x] stop button
* [x] baud rate selection
* [x] port selection

These buttons will link to the `COPISCore` commands once they are implemented (#72 & #73).

**Comment by inchkev** [comment]
I think the play, pause, and stop button are wired already?

**Comment by djihbril** [comment]
Resolved
